{{
    config(
        materialized= 'incremental',
        unique_key = 'ASSIGNMENT_KEY'
    )
}}

select
  distinct
  {{ dbt_utils.generate_surrogate_key(['ASSIGNMENT_NAME','ASSIGNMENT_EMPLOYMENT_CATEGORY','ASSIGNMENT_CURRENT_CHG_ACTION','ASSIGNMENT_CURRENT_CHG_REASON','ASSIGNMENT_STATUS','HOURLY_SALARIED','GRADE_NAME','ASSIGNMENT_CURRENT_EFFECTIVE_DATE'
]) }} as ASSIGNMENT_KEY,
ASSIGNMENT_NAME, ASSIGNMENT_EMPLOYMENT_CATEGORY, ASSIGNMENT_CURRENT_CHG_ACTION, 
ASSIGNMENT_CURRENT_CHG_REASON, ASSIGNMENT_STATUS,HOURLY_SALARIED, GRADE_NAME , ASSIGNMENT_CURRENT_EFFECTIVE_DATE
from {{ ref('src_combined') }}



-- WITH ASSIGNMENT AS (
-- SELECT distinct  ASSIGNMENT_NAME, ASSIGNMENT_EMPLOYMENT_CATEGORY, ASSIGNMENT_CURRENT_CHG_ACTION, 
-- ASSIGNMENT_CURRENT_CHG_REASON, ASSIGNMENT_STATUS,HOURLY_SALARIED, GRADE_NAME , ASSIGNMENT_CURRENT_EFFECTIVE_DATE
-- FROM
-- {{ref('src_combined')}}
-- )
-- SELECT *,ROW_NUMBER() OVER (ORDER BY ASSIGNMENT_NAME, ASSIGNMENT_EMPLOYMENT_CATEGORY, ASSIGNMENT_CURRENT_CHG_ACTION, 
-- ASSIGNMENT_CURRENT_CHG_REASON, ASSIGNMENT_STATUS,HOURLY_SALARIED, GRADE_NAME ,ASSIGNMENT_CURRENT_EFFECTIVE_DATE) ASSIGNMENT_KEY

-- FROM ASSIGNMENT